version: '4'
services:
  postgres:
    image: postgres:13
    container_name: nest-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - pary-nest-network
    env_file:
      - ./.env

  nestjs:
    build:
      context: .
      dockerfile: nest.Dockerfile
    env_file:
      - ./.env
    container_name: nest-back
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - pary-nest-network

networks:
  pary-nest-network:
    driver: bridge
